# Generated by Django 4.1 on 2022-08-31 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfast',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='dinner',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='user_id',
        ),
    ]
