# Generated by Django 4.1 on 2022-08-31 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_remove_breakfast_user_id_remove_dinner_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intakediet',
            name='user_id',
        ),
    ]
