# Generated by Django 4.1 on 2022-09-04 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0003_remove_intakediet_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Age', models.IntegerField(null=True)),
                ('Expertise', models.CharField(max_length=100)),
                ('Experience', models.IntegerField(null=True)),
                ('Name', models.CharField(max_length=100)),
                ('Fees', models.IntegerField(null=True)),
                ('profile', models.ImageField(upload_to='static/health/image/img.png')),
            ],
        ),
        migrations.CreateModel(
            name='WalletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('amount_transaction', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterIntakeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Glass', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.usermaster')),
            ],
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
