# Generated by Django 4.1 on 2022-09-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_trainermodel_walletmodel_waterintakemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletmodel',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
