# Generated by Django 4.1 on 2022-09-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_walletmodel_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletmodel',
            name='Balance',
            field=models.FloatField(null=True),
        ),
    ]
