# Generated by Django 4.1 on 2022-09-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_remove_walletmodel_balance_usermodel_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='expirydate',
            field=models.DateTimeField(null=True),
        ),
    ]
