# Generated by Django 4.1 on 2022-09-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_usermodel_expirydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainermodel',
            name='Fees1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trainermodel',
            name='Fees2',
            field=models.IntegerField(null=True),
        ),
    ]
