# Generated by Django 4.1 on 2022-09-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_trainermodel_fees1_trainermodel_fees2'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainermodel',
            name='profile1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
