# Generated by Django 4.1 on 2022-09-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0017_alter_savevideo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='pic',
            field=models.ImageField(null=True, upload_to='static/health/image'),
        ),
    ]
