# Generated by Django 4.1 on 2022-09-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0018_videos_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='savevideo',
            name='pic',
            field=models.ImageField(null=True, upload_to='static/health/image'),
        ),
    ]
