# Generated by Django 4.1 on 2022-09-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0019_savevideo_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterintakemodel',
            name='quantity',
            field=models.FloatField(null=True),
        ),
    ]
