# Generated by Django 4.1 on 2022-09-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0020_alter_waterintakemodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterintakemodel',
            name='dat',
            field=models.DateField(null=True),
        ),
    ]
